# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accesstimes',
            field=models.IntegerField(default=0),
        ),
    ]
