# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_post_accesstimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20, verbose_name='\u6635\u79f0')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('S', 'secrecy')], default='S', max_length=10, verbose_name='\u6027\u522b')),
                ('introduce', models.CharField(blank=True, max_length=300, verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='\u624b\u673a')),
                ('image', models.ImageField(blank=True, upload_to='image/user/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
