# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, storage=system.storage.ImageStorage(), upload_to='image/user'),
        ),
    ]
