# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171023_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.TextField(blank=True, max_length=300, verbose_name='\u4e2a\u4eba\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.CharField(blank=True, default='\u8272\u5373\u662f\u7a7a\uff0c\u7a7a\u5373\u662f\u8272', max_length=50, verbose_name='\u5ea7\u53f3\u94ed'),
        ),
    ]
