# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171023_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='\u672a\u540d', max_length=10, verbose_name='\u6635\u79f0'),
        ),
    ]
