# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=60, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
