# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171024_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': 'VerifyRecord', 'verbose_name_plural': 'VerifyRecord'},
        ),
    ]
