# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171026_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u73b0\u4f4f'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobby',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7231\u597d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u5bb6\u4e61'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u804c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.TextField(blank=True, max_length=200, verbose_name='\u4e2a\u4eba\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.CharField(blank=True, default='\u8272\u5373\u662f\u7a7a\uff0c\u7a7a\u5373\u662f\u8272', max_length=30, verbose_name='\u5ea7\u53f3\u94ed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u6635\u79f0'),
        ),
    ]
