# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171030_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='\u697c\u5c42'),
        ),
    ]
