# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_comment_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('self', '\u539f\u521b'), ('reprint', '\u8f6c\u8f7d'), ('collect', '\u6536\u85cf')], default='reprint', max_length=10)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_class', to='blog.Post')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_class', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
