# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_picturerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecord',
            name='body',
            field=models.TextField(max_length=300, verbose_name='\u7559\u8a00'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '\u7537'), ('F', '\u5973'), ('S', '\u4fdd\u5bc6')], default='S', max_length=2, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u624b\u673a'),
        ),
    ]
