# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_userrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstimes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Uv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstimes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='accesstimes',
        ),
        migrations.AddField(
            model_name='pv',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='blog.Post'),
        ),
    ]
