# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_auto_20171115_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True)),
                ('collect_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_collect', to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='postclass',
            name='post_type',
            field=models.CharField(choices=[('self', '\u539f\u521b'), ('reprint', '\u8f6c\u8f7d')], default='self', max_length=10),
        ),
    ]
