# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20171122_1424'),
    ]

    operations = [
        #migrations.RenameModel(
            #old_name='EmailVerifyRecord',
            #new_name='VerifyRecord',
        #),
    ]
